"""upd Users

Revision ID: 0229866f951b
Revises: 2f247b1ad7fd
Create Date: 2021-12-27 15:23:55.491874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0229866f951b'
down_revision = '2f247b1ad7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_name', table_name='users')
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=False)
    # ### end Alembic commands ###
