"""add foreignkey

Revision ID: 24613798e08c
Revises: 95045a9ebb9b
Create Date: 2021-12-17 01:03:56.535749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24613798e08c'
down_revision = '95045a9ebb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_rigths_id_script', table_name='access_rigths')
    op.drop_index('ix_access_rigths_id_user', table_name='access_rigths')
    op.create_foreign_key(None, 'access_rigths', 'users', ['id_user'], ['id'])
    op.create_foreign_key(None, 'access_rigths', 'scripts', ['id_script'], ['id'])
    op.drop_index('ix_protocols_id_work', table_name='protocols')
    op.create_foreign_key(None, 'protocols', 'work_status', ['id_work'], ['id'])
    op.drop_index('ix_scripts_id_wt', table_name='scripts')
    op.create_foreign_key(None, 'scripts', 'work_type', ['id_wt'], ['id'])
    op.drop_index('ix_user_data_id_work', table_name='user_data')
    op.create_foreign_key(None, 'user_data', 'work_status', ['id_work'], ['id'])
    op.drop_index('ix_work_status_id_device', table_name='work_status')
    op.create_foreign_key(None, 'work_status', 'devices', ['id_device'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_status', type_='foreignkey')
    op.create_index('ix_work_status_id_device', 'work_status', ['id_device'], unique=False)
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.create_index('ix_user_data_id_work', 'user_data', ['id_work'], unique=False)
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.create_index('ix_scripts_id_wt', 'scripts', ['id_wt'], unique=False)
    op.drop_constraint(None, 'protocols', type_='foreignkey')
    op.create_index('ix_protocols_id_work', 'protocols', ['id_work'], unique=False)
    op.drop_constraint(None, 'access_rigths', type_='foreignkey')
    op.drop_constraint(None, 'access_rigths', type_='foreignkey')
    op.create_index('ix_access_rigths_id_user', 'access_rigths', ['id_user'], unique=False)
    op.create_index('ix_access_rigths_id_script', 'access_rigths', ['id_script'], unique=False)
    # ### end Alembic commands ###
