"""upd relatyonship

Revision ID: 2f247b1ad7fd
Revises: d2156155bd46
Create Date: 2021-12-27 13:39:45.705351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f247b1ad7fd'
down_revision = 'd2156155bd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'positions_employees', ['position_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions_employees', type_='unique')
    # ### end Alembic commands ###
