"""linux

Revision ID: 31aef324b21c
Revises: 
Create Date: 2022-01-19 19:09:15.275636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31aef324b21c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_name')
    )
    op.create_table('work_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Text(), nullable=True),
    sa.Column('modification', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('id_work_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_work_type'], ['work_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_order_number'), 'devices', ['order_number'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wt', sa.Integer(), nullable=True),
    sa.Column('script_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_wt'], ['work_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('id_employee_position', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_employee_position'], ['positions_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('access_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_work_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_work_type'], ['work_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_device', sa.Integer(), nullable=True),
    sa.Column('work_status', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checked_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('checked_point_name', sa.Text(), nullable=True),
    sa.Column('checked_point_parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_work'], ['work_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('protocol_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_work'], ['work_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('base_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_work'], ['work_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checked_point_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_checked_point', sa.Integer(), nullable=True),
    sa.Column('current_method', sa.Text(), nullable=True),
    sa.Column('next_method', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point'], ['checked_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checked_point_data')
    op.drop_table('user_data')
    op.drop_table('protocols')
    op.drop_table('checked_point')
    op.drop_table('work_status')
    op.drop_table('access_rights')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_table('users')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_order_number'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('work_type')
    op.drop_table('positions_employees')
    # ### end Alembic commands ###
