"""Add page_content

Revision ID: 3271b78fb8ed
Revises: 31aef324b21c
Create Date: 2022-01-22 16:16:39.360103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3271b78fb8ed'
down_revision = '31aef324b21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_point_data', sa.Column('page_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checked_point_data', 'page_content')
    # ### end Alembic commands ###
