"""add path to scripts

Revision ID: 3702bc15dd98
Revises: fa440370fe37
Create Date: 2022-01-11 15:23:15.597716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3702bc15dd98'
down_revision = 'fa440370fe37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'path')
    # ### end Alembic commands ###
