"""add lazy_join

Revision ID: 39f93a906252
Revises: 0229866f951b
Create Date: 2021-12-27 22:44:56.172420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f93a906252'
down_revision = '0229866f951b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_script', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_script'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('access_rigths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_rigths',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_script', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_script'], ['scripts.id'], name='access_rigths_id_script_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='access_rigths_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='access_rigths_pkey')
    )
    op.drop_table('access_rights')
    # ### end Alembic commands ###
