"""test

Revision ID: 3abc228ab500
Revises: ded8d9e8f121
Create Date: 2022-01-14 13:46:10.792635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abc228ab500'
down_revision = 'ded8d9e8f121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point_data1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_checked_point', sa.Integer(), nullable=True),
    sa.Column('current_method', sa.Text(), nullable=True),
    sa.Column('next_method', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point'], ['checked_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checked_point_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point_data',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('next_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_checked_point', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point'], ['checked_point.id'], name='checked_point_data_id_checked_point_fkey')
    )
    op.drop_table('checked_point_data1')
    # ### end Alembic commands ###
