"""test 2

Revision ID: 5f2fc34a7139
Revises: 3abc228ab500
Create Date: 2022-01-14 13:49:47.095057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2fc34a7139'
down_revision = '3abc228ab500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_checked_point', sa.Integer(), nullable=True),
    sa.Column('current_method', sa.Text(), nullable=True),
    sa.Column('next_method', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point'], ['checked_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checked_point_data1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point_data1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_checked_point', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point'], ['checked_point.id'], name='checked_point_data1_id_checked_point_fkey'),
    sa.PrimaryKeyConstraint('id', name='checked_point_data1_pkey')
    )
    op.drop_table('checked_point_data')
    # ### end Alembic commands ###
