"""ScriptTree and UserAnswer

Revision ID: 7cff234ff2db
Revises: 63d740d000bd
Create Date: 2021-12-21 18:55:03.898256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cff234ff2db'
down_revision = '63d740d000bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.Text(), nullable=True),
    sa.Column('argument_of_function', sa.Text(), nullable=True),
    sa.Column('current_point', sa.Text(), nullable=True),
    sa.Column('next_point', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer')
    op.drop_table('script_tree')
    # ### end Alembic commands ###
