"""rename model

Revision ID: 81d407e94525
Revises: be3750fbda4d
Create Date: 2022-01-14 12:14:09.497565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d407e94525'
down_revision = 'be3750fbda4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_checked_point_tree', sa.Integer(), nullable=True),
    sa.Column('current_method', sa.Text(), nullable=True),
    sa.Column('next_method', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_checked_point_tree'], ['script_tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('function_data')
    op.add_column('script_tree', sa.Column('checked_point_name', sa.Text(), nullable=True))
    op.add_column('script_tree', sa.Column('checked_point_parameters', sa.Text(), nullable=True))
    op.drop_column('script_tree', 'function_name')
    op.drop_column('script_tree', 'function_parameters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_tree', sa.Column('function_parameters', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('script_tree', sa.Column('function_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('script_tree', 'checked_point_parameters')
    op.drop_column('script_tree', 'checked_point_name')
    op.create_table('function_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_function_tree', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_function_tree'], ['script_tree.id'], name='function_data_id_function_tree_fkey'),
    sa.PrimaryKeyConstraint('id', name='function_data_pkey')
    )
    op.drop_table('checked_point_data')
    # ### end Alembic commands ###
