"""create table

Revision ID: 94d9d5fb35c7
Revises: 
Create Date: 2021-12-17 00:35:24.662134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d9d5fb35c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ser_num', sa.Text(), nullable=True),
    sa.Column('app_num', sa.Text(), nullable=True),
    sa.Column('modification', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_app_num'), 'devices', ['app_num'], unique=False)
    op.create_index(op.f('ix_devices_date'), 'devices', ['date'], unique=False)
    op.create_index(op.f('ix_devices_modification'), 'devices', ['modification'], unique=False)
    op.create_index(op.f('ix_devices_ser_num'), 'devices', ['ser_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_ser_num'), table_name='devices')
    op.drop_index(op.f('ix_devices_modification'), table_name='devices')
    op.drop_index(op.f('ix_devices_date'), table_name='devices')
    op.drop_index(op.f('ix_devices_app_num'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
