"""create ALL table

Revision ID: 95045a9ebb9b
Revises: 94d9d5fb35c7
Create Date: 2021-12-17 01:00:00.073688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95045a9ebb9b'
down_revision = '94d9d5fb35c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_rigths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_script', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_rigths_id_script'), 'access_rigths', ['id_script'], unique=False)
    op.create_index(op.f('ix_access_rigths_id_user'), 'access_rigths', ['id_user'], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('protocol_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_id_work'), 'protocols', ['id_work'], unique=False)
    op.create_index(op.f('ix_protocols_path'), 'protocols', ['path'], unique=False)
    op.create_index(op.f('ix_protocols_protocol_name'), 'protocols', ['protocol_name'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wt', sa.Integer(), nullable=True),
    sa.Column('script_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id_wt'), 'scripts', ['id_wt'], unique=False)
    op.create_index(op.f('ix_scripts_path'), 'scripts', ['path'], unique=False)
    op.create_index(op.f('ix_scripts_script_name'), 'scripts', ['script_name'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('base_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_base_name'), 'user_data', ['base_name'], unique=False)
    op.create_index(op.f('ix_user_data_id_work'), 'user_data', ['id_work'], unique=False)
    op.create_index(op.f('ix_user_data_path'), 'user_data', ['path'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_path'), 'users', ['path'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('work_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_type_work_type_name'), 'work_type', ['work_type_name'], unique=False)
    op.create_table('work_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_device', sa.Integer(), nullable=True),
    sa.Column('work_status', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_status_id_device'), 'work_status', ['id_device'], unique=False)
    op.create_index(op.f('ix_work_status_work_status'), 'work_status', ['work_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_status_work_status'), table_name='work_status')
    op.drop_index(op.f('ix_work_status_id_device'), table_name='work_status')
    op.drop_table('work_status')
    op.drop_index(op.f('ix_work_type_work_type_name'), table_name='work_type')
    op.drop_table('work_type')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_path'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_data_path'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_id_work'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_base_name'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_index(op.f('ix_scripts_script_name'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_path'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_id_wt'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_protocols_protocol_name'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_path'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_id_work'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_access_rigths_id_user'), table_name='access_rigths')
    op.drop_index(op.f('ix_access_rigths_id_script'), table_name='access_rigths')
    op.drop_table('access_rigths')
    # ### end Alembic commands ###
