"""rename id

Revision ID: ad2e2c1e8674
Revises: d9a95c24ed96
Create Date: 2022-01-14 12:50:42.375749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2e2c1e8674'
down_revision = 'd9a95c24ed96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_point_data', sa.Column('id_checked_point', sa.Integer(), nullable=True))
    op.drop_constraint('unique_checked_point_data_id_checked_point_tree', 'checked_point_data', type_='unique')
    op.drop_constraint('checked_point_data_id_checked_point_tree_fkey', 'checked_point_data', type_='foreignkey')
    op.create_foreign_key(None, 'checked_point_data', 'checked_point', ['id_checked_point'], ['id'])
    op.drop_column('checked_point_data', 'id_checked_point_tree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_point_data', sa.Column('id_checked_point_tree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checked_point_data', type_='foreignkey')
    op.create_foreign_key('checked_point_data_id_checked_point_tree_fkey', 'checked_point_data', 'checked_point', ['id_checked_point_tree'], ['id'])
    op.create_unique_constraint('unique_checked_point_data_id_checked_point_tree', 'checked_point_data', ['id_checked_point_tree'])
    op.drop_column('checked_point_data', 'id_checked_point')
    # ### end Alembic commands ###
