"""upd WorkType

Revision ID: b64616543009
Revises: 39f93a906252
Create Date: 2022-01-10 12:31:24.862541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64616543009'
down_revision = '39f93a906252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_rights', sa.Column('id_work_type', sa.Integer(), nullable=True))
    op.drop_constraint('access_rights_id_script_fkey', 'access_rights', type_='foreignkey')
    op.create_foreign_key(None, 'access_rights', 'work_type', ['id_work_type'], ['id'])
    op.drop_column('access_rights', 'id_script')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_rights', sa.Column('id_script', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'access_rights', type_='foreignkey')
    op.create_foreign_key('access_rights_id_script_fkey', 'access_rights', 'scripts', ['id_script'], ['id'])
    op.drop_column('access_rights', 'id_work_type')
    # ### end Alembic commands ###
