"""add path to scripts

Revision ID: be3750fbda4d
Revises: 3702bc15dd98
Create Date: 2022-01-12 15:53:04.949631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3750fbda4d'
down_revision = '3702bc15dd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.Text(), nullable=True),
    sa.Column('function_parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_work'], ['work_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_function_tree', sa.Integer(), nullable=True),
    sa.Column('current_method', sa.Text(), nullable=True),
    sa.Column('next_method', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_function_tree'], ['script_tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('function_data')
    op.drop_table('script_tree')
    # ### end Alembic commands ###
