"""new models

Revision ID: d10129b4446d
Revises: e8b11dfbc2da
Create Date: 2021-12-27 12:19:15.105733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10129b4446d'
down_revision = 'e8b11dfbc2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('id_employee_position', sa.Integer(), nullable=True))
    op.drop_column('users', 'employee_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_position', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'id_employee_position')
    op.drop_table('positions_employees')
    # ### end Alembic commands ###
