"""add relatyonship

Revision ID: d2156155bd46
Revises: d10129b4446d
Create Date: 2021-12-27 13:29:29.244845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2156155bd46'
down_revision = 'd10129b4446d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'positions_employees', ['id_employee_position'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
