"""rename model

Revision ID: d9a95c24ed96
Revises: 81d407e94525
Create Date: 2022-01-14 12:40:17.524363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a95c24ed96'
down_revision = '81d407e94525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_work', sa.Integer(), nullable=True),
    sa.Column('checked_point_name', sa.Text(), nullable=True),
    sa.Column('checked_point_parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_work'], ['work_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('script_tree')
    op.alter_column('checked_point_data', 'id_checked_point_tree',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checked_point_data', 'current_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checked_point_data', 'next_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checked_point_data', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('unique_checked_point_data_id', 'checked_point_data', type_='unique')
    op.create_foreign_key(None, 'checked_point_data', 'checked_point', ['id_checked_point_tree'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checked_point_data', type_='foreignkey')
    op.create_unique_constraint('unique_checked_point_data_id', 'checked_point_data', ['id'])
    op.alter_column('checked_point_data', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checked_point_data', 'next_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checked_point_data', 'current_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checked_point_data', 'id_checked_point_tree',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('script_tree',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_work', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checked_point_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('checked_point_parameters', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('id', name='unique_script_tree_id'),
    sa.UniqueConstraint('id_work', name='unique_script_tree_id_work')
    )
    op.drop_table('checked_point')
    # ### end Alembic commands ###
