"""upd Device

Revision ID: fa440370fe37
Revises: 2f38e9cd2bf6
Create Date: 2022-01-10 16:25:33.562651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa440370fe37'
down_revision = '2f38e9cd2bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('id_work_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'work_type', ['id_work_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'id_work_type')
    # ### end Alembic commands ###
